### PR TITLE
Progress monitor

### PR DESCRIPTION
**Pull request by dsschult**
script to dump NERSC stats from file catalog to elasticsearch

### CODE REVIEW

**Comment by dsschult** [comment]
lots of beautiful flake8 errors now that I've turned that on

**Comment by blinkdog** [comment]
> lots of beautiful flake8 errors now that I've turned that on

And all of those in stuff that we don't use.

The file under `doc/` is an old script to archive with Rucio
The files under `jadetools/` is a copy of what we had on Cori NERSC for disk archiving back in the day.

Neither of these is used now. If the easiest solution is "let's delete them and look back in version control if we ever need them again" you've got my :+1: to do that in this PR.

**Comment by dsschult** [comment]
> > lots of beautiful flake8 errors now that I've turned that on
> 
> And all of those in stuff that we don't use.
> 
> The file under `doc/` is an old script to archive with Rucio The files under `jadetools/` is a copy of what we had on Cori NERSC for disk archiving back in the day.
> 
> Neither of these is used now. If the easiest solution is "let's delete them and look back in version control if we ever need them again" you've got my +1 to do that in this PR.

I found the "exclude" option, which is easier.

**Comment by dsschult** [comment]
Some updates, and a rebase on master.

**Comment by dsschult** [comment]
I think this is finally ready to convert to a k8s cron job.  I should have all the bugs worked out now.

**Review by blinkdog — APPROVED** [review]
LGTM.

**Pull request merged**
